from Bio import SeqIO
import re

Filename = 'Lactobacillus acidophilus.fasta'
Handle = open(Filename)
DNAList = []
for seq_record in SeqIO.parse(Handle, "fasta"):
    DNAList.append(str(seq_record.seq))
string = "TTTTTTTACGTAGGCATTGACGATACGCAATTTCAAGTTTTCTTCTTTGAGTTGCTGGATCTGCTTCTCTAAATCTTTGCGCGATGTTTGGGATTGCTTCTTCTGACTCATGAACGGAATGCCGTCCTTTCTTCTTGATAACGACATTATACCCATTTTTCTTATATTCGCGAATCCAATTATACAAGATACCGTTGCTTCTTAGTCCCAGATCTAAAGACAACTGATTAATTGAATTATTACCAGTTAATGATCTAACAATGGCTTTTTCCTTAAATTCTTTGGTAAACAATTCCTTAGATTTATCATAGATTTCGATCCCATGACGATCTATTAAATTAACCATATATTGTAGGGTAGAACGATTTAATTTTATTTCAGAAGCGATTACAGATAAGGA"
A = DNAList[0]
math = re.split(string,A)
s1 = math[0]
s2 = math[1]
s3 = math[2]

for i in range(1000000):
    if s3[:i] == s2[:i]:# and s2[:i] == s3[:i]:
        pass
    else:
        print(i)
        break
print( "Length of the DNA is", len(DNAList[0]))